local ui = require("ugaterm.ui").new()

local function num_win()
  return vim.fn.winnr("$")
end

describe("Test for terminal", function()
  before_each(function()
    vim.cmd("silent %bwipeout!")
    ui = require("ugaterm.ui").new()
  end)

  it("open/hide", function()
    assert.equals(1, num_win())
    ui:open()
    assert.equals(2, num_win())
    ui:hide()
    assert.equals(1, num_win())
  end)

  it("toggle", function()
    assert.equals(1, num_win())
    ui:toggle()
    assert.equals(2, num_win())
    ui:toggle()
    assert.equals(1, num_win())
  end)

  it("new_open", function()
    ui:open()
    assert.equals("terminal://1", vim.api.nvim_buf_get_name(0))
    ui:new_open()
    assert.equals("terminal://2", vim.api.nvim_buf_get_name(0))
    ui:hide()
  end)

  it("new_open with name", function()
    ui:open()
    assert.equals("terminal://1", vim.api.nvim_buf_get_name(0))
    ui:new_open("terminal://foo")
    assert.equals("terminal://foo", vim.api.nvim_buf_get_name(0))
    ui:hide()
  end)

  it("delete", function()
    ui:open()
    assert.equals("terminal://1", vim.api.nvim_buf_get_name(0))
    ui:new_open()
    assert.equals("terminal://2", vim.api.nvim_buf_get_name(0))
    ui:delete()
    assert.equals("terminal://1", vim.api.nvim_buf_get_name(0))
    ui:hide()
  end)

  describe("return to the original window", function()
    ---@param callback fun(orig_winid: integer)
    local function assert_keep_win(callback)
      local orig_winid = vim.api.nvim_get_current_win()
      callback(orig_winid)
      assert.equals(orig_winid, vim.api.nvim_get_current_win())
    end

    it("hide", function()
      assert_keep_win(function(orig_winid)
        vim.cmd.vsplit()
        vim.fn.win_gotoid(orig_winid)
        ui:open()
        ui:hide()
      end)
    end)

    it("delete", function()
      assert_keep_win(function(orig_winid)
        vim.cmd.vsplit()
        vim.fn.win_gotoid(orig_winid)
        ui:open()
        ui:new_open()
        ui:delete()
        ui:delete()
      end)
    end)

    describe("keep the position if outside the terminal", function()
      it("hide", function()
        assert_keep_win(function(orig_winid)
          vim.cmd.vsplit()
          ui:open()
          vim.fn.win_gotoid(orig_winid)
          ui:hide()
        end)
      end)

      it("delete", function()
        assert_keep_win(function(orig_winid)
          vim.cmd.vsplit()
          ui:open()
          vim.fn.win_gotoid(orig_winid)
          ui:delete()
        end)
      end)
    end)
  end)
end)
